TILES_PTR     EQU $8800
CHARS_PTR     EQU $9000
SCREEN_PTR    EQU $9800

SCROLL_FLAG_0 EQU $80
SCROLLPOS_YOU EQU $00
SCROLLPOS_OP  EQU 112

PLANE_CRTO    EQU 0 ; current orientation
PLANE_UP      EQU 1
PLANE_RIGHT   EQU 2
PLANE_DOWN    EQU 3
PLANE_LEFT    EQU 4

PLANE_ID_0    EQU 0
PLANE_ID_1    EQU 1
PLANE_ID_2    EQU 2
PLANE_ID_3    EQU 3 ; ! DEBUG ONLY

